2013학년도 1학기 과제물(온라인제출용)
 교과목명 : 탐색적 자료분석
 학    번 : 201435-341832
 성    명 : 지용기  
========================================================
※ 다음 자료는 28명의 학생들을 대상으로 휴대전화 사용관련 자료를 설문하여 조사한 자료이다. 휴대전화를 통한 모바일강의 수강상태는 수강시 1, 미수강시 0으로 코딩되었다.

학생번호 : 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
휴대전화 사용기간 : 3.6, 15.4, 11.3, 10.3,  5.8,  8.0, 14.6, 11.4,  7.2,  5.5, 11.1, 16.5, 10.9,  2.5, 10.8,  4.7,  5.5,  4.5,  9.0,  6.8
나이 : 25, 26, 32, 28, 26, 45, 30, 35, 28, 32, 37, 43, 25, 49, 35, 37, 26, 21, 18, 34
수강상태 : 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1



## 1. 위 자료의 나이의 줄기-잎-그림을 작성하라.(5점)

```{r}
stnum <- c( 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 )
period <- c( 3.6, 15.4, 11.3, 10.3,  5.8,  8.0, 14.6, 11.4,  7.2,  5.5, 11.1, 16.5, 10.9,  2.5, 10.8,  4.7,  5.5,  4.5,  9.0,  6.8 )
age <- c( 25, 26, 32, 28, 26, 45, 30, 35, 28, 32, 37, 43, 25, 49, 35, 37, 26, 21, 18, 34 )
sukang <- c( 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1 )

stem( age ) 
```

## 2. 수강 상태에 따른 사용기간의 상자그림을 작성하고 해석하라.(5점)

```{r}
yes_period <- period[ sukang[]==1 ]
no_period <- period[ sukang[]==0 ]
boxplot(yes_period, no_period,  names=c("수강", "미수강"))
title("수강 상태에 따른 사용기간의 상자그림")
```

## 3. 나이에 따른 휴대전화 사용기간의 산점도와 저항회귀직선을 구하고 해석하라.(10점)
```{r}
plot(age ~ period,  type="p", xlab="나이", ylab="휴대전화 사용기간" ) 
#install.packages("LearnEDA")
library(LearnEDA)
rline(age, period,iter=1)
```

## 4. 다섯수치요약을 구하고 분포개형의 특징을 설명하고 적합한 재표현을 구하라.(5점)
```{r}
summary(period)
summary(age)
```

## 5. EDA의 네가지 주제를 설명하라(5점)



